### ISSUE TITLE
GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to api.telegram.org port 443: Timed out 

### ISSUE THREAD

**Issue by farshidahmadianpin** [laravel-notification-channels/telegram#74]
hi, thank you for this nice package

i have this error in local host. how i can fix it?

The communication with Telegram failed. `GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to api.telegram.org port 443: Timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in

**Comment by irazasyed** [comment]
Hey @farshidahmadianpin,

I think it's happening because Telegram is blocked in your country.

You can either host the app outside your country where it isn't blocked or setup a proxy. Since we use Guzzle, you can set an env var with your proxy. Please refer these [docs](http://docs.guzzlephp.org/en/stable/quickstart.html#environment-variables) for more details on how to set it up. 

Hope that helps!

**Comment by farshidahmadianpin** [comment]
thank you
